/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.in by autoheader.  */
/* accconfig.h -- `autoheader' will generate config.h.in for tsocks . */

/* Allow tsocks to generate messages to stderr when errors are
encountered, this is really important and should only be disabled if
you're REALLY sure. It can also be turned off at run time, see the man
page for details */
#define ALLOW_MSG_OUTPUT 1

/* Allow TSOCKS_CONF_FILE in environment to specify config file
location */
//#define ALLOW_ENV_CONFIG 1

/* Use _GNU_SOURCE to define RTLD_NEXT, mostly for RH7 systems */
/* #undef USE_GNU_SOURCE */

/* Configure the system resolver to use TCP queries on startup, this
allows socksified DNS */
#define USE_SOCKS_DNS 0

/* Prototype and function header for connect function */
#define CONNECT_SIGNATURE int __fd, const struct sockaddr * __addr, socklen_t __len

/* The type of socket structure pointer to use to call the
 * real connect */
#define CONNECT_SOCKARG struct sockaddr *

/* Prototype and function header for select function */
#define SELECT_SIGNATURE int n, fd_set *readfds, fd_set *writefds, fd_set *exceptfds, struct timeval *timeout

/* Prototype and function header for poll function */
#define POLL_SIGNATURE struct pollfd ufds[], nfds_t nfds, int timeout

/* Prototype and function header for close function */
#define CLOSE_SIGNATURE int fd

/* Prototype and function header for getpeername function */
#define GETPEERNAME_SIGNATURE int __fd, struct sockaddr * __name, socklen_t *__namelen

/* Work out which function we have for conversion from string IPs to
numerical ones */
/* #undef HAVE_INET_ADDR */
#define HAVE_INET_ATON 1

/* We use strsep which isn't on all machines, but we provide our own
definition of it for those which don't have it, this causes us to define
our version */
/* #undef DEFINE_STRSEP */

/* Should we resolve DNS entries in a way which works well with tor? */
#define USE_TOR_DNS 0

/* Allow the use of DNS names in the socks configuration file for socks
servers. This doesn't work if socksified DNS is enabled for obvious
reasons, it also introduces overhead, but people seem to want it */
#define HOSTNAMES 0

/* We need the gethostbyname() function to do dns lookups in tsocks or
in inspectsocks */
#define HAVE_GETHOSTBYNAME 1

/* Location of configuration file (typically /etc/tsocks.conf) */
#define CONF_FILE "/etc/tsocks.conf"

/* Define to indicate the correct signature for gethostbyname_r */
/* #undef HAVE_FUNC_GETHOSTBYNAME_R_6 */
/* #undef HAVE_FUNC_GETHOSTBYNAME_R_5 */
/* #undef HAVE_FUNC_GETHOSTBYNAME_R_3 */

/* Signatures for name resolution stuff */
#define GETHOSTBYNAME_SIGNATURE const char *name
#define GETADDRINFO_SIGNATURE const char *node, const char *service, void *hints, void *res
#define GETIPNODEBYNAME_SIGNATURE const char *name, int af, int flags, int *error_num


/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the `dl' library (-ldl). */
#define HAVE_LIBDL 1

/* Define to 1 if you have the `socket' library (-lsocket). */
/* #undef HAVE_LIBSOCKET */

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the `mmap' function. */
#define HAVE_MMAP 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the `strcasecmp' function. */
#define HAVE_STRCASECMP 1

/* Define to 1 if you have the `strcspn' function. */
#define HAVE_STRCSPN 1

/* Define to 1 if you have the `strdup' function. */
#define HAVE_STRDUP 1

/* Define to 1 if you have the `strerror' function. */
#define HAVE_STRERROR 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the `strncasecmp' function. */
#define HAVE_STRNCASECMP 1

/* Define to 1 if you have the `strspn' function. */
#define HAVE_STRSPN 1

/* Define to 1 if you have the `strtol' function. */
#define HAVE_STRTOL 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT ""

/* Define to the full name of this package. */
#define PACKAGE_NAME ""

/* Define to the full name and version of this package. */
#define PACKAGE_STRING ""

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME ""

/* Define to the version of this package. */
#define PACKAGE_VERSION ""

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1
